### ISSUE TITLE
RIAS Plugin support

### ISSUE THREAD

**Issue by PavelZhuravlev** [ivodolenc/nuxt-lazysizes#8] opened 2021-04-21 22:44 UTC
Thank you for creating lazysizes wrapper for Nuxt.js!
Could I ask you to add Rias Plugin support, please?

**Comment by ivodolenc** [comment] 2021-04-22 13:36
Hi, thanks for you interest in this module.

This is a duplicate of #5 and as mentioned there, I'm definitely interested in adding support for additional plugins, but I'm currently focused on other things, so this isn't a top priority.

If I catch some extra time this weekend, I might add support for some plugins (can't promise anything). I have to explore docs and examples first because there are a lot of extra plugins, and then see how to implement them in the current code.

In the meantime, if you're interested in creating `PR`, I'll be more than happy to merge it.

Also, I would close this in a favour of #5 and move the discussion there.

**Closed by ivodolenc** 2021-04-22 13:36 UTC
